In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data=pd.read_csv('cars_clus.csv')

In [3]:
data

,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition
0,Acura,Integra,16.919,16.360,0,21.50,1.8,140,101.2,67.3,172.4,2.639,13.2,28.0,2.828,0
1,Acura,TL,39.384,19.875,0,28.40,3.2,225,108.1,70.3,192.9,3.517,17.2,25.0,3.673,0
2,Acura,RL,8.588,29.725,0,42.00,3.5,210,114.6,71.4,196.6,3.850,18.0,22.0,2.150,0
3,Audi,A4,20.397,22.255,0,23.99,1.8,150,102.6,68.2,178.0,2.998,16.4,27.0,3.015,0
4,Audi,A6,18.780,23.555,0,33.95,2.8,200,108.7,76.1,192.0,3.561,18.5,22.0,2.933,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Volkswagen,Golf,9.761,11.425,0,14.90,2.0,115,98.9,68.3,163.3,2.767,14.5,26.0,2.278,0
113,Volkswagen,Jetta,83.721,13.240,0,16.70,2.0,115,98.9,68.3,172.3,2.853,14.5,26.0,4.427,0
114,Volkswagen,Passat,51.102,16.725,0,21.20,1.8,150,106.4,68.5,184.1,3.043,16.4,27.0,3.934,0
115,Volkswagen,Cabrio,9.569,16.575,0,19.99,2.0,115,97.4,66.7,160.4,3.079,13.7,26.0,2.259,0
116,Volkswagen,GTI,5.596,13.760,0,17.50,2.0,115,98.9,68.3,163.3,2.762,14.6,26.0,1.722,0

In [4]:
data.describe()

,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition
count,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.000000,117.0
mean,59.112316,18.031538,0.247863,25.969487,3.048718,181.282051,107.326496,71.189744,187.717949,3.324051,17.812821,24.117949,3.401179,0.0
std,75.058933,11.605632,0.433629,14.149699,1.055169,58.591786,8.050588,3.530151,13.849926,0.597177,3.794609,4.404164,1.337862,0.0
min,0.110000,5.160000,0.000000,9.235000,1.000000,55.000000,92.600000,62.600000,149.400000,1.895000,10.300000,15.000000,-2.207000,0.0
25%,16.767000,11.240000,0.000000,16.980000,2.200000,140.000000,102.400000,68.500000,177.500000,2.911000,15.300000,22.000000,2.819000,0.0
50%,32.299000,14.010000,0.000000,21.665000,3.000000,175.000000,107.000000,70.400000,187.800000,3.340000,17.200000,24.000000,3.475000,0.0
75%,76.029000,19.875000,0.000000,29.465000,3.800000,210.000000,111.600000,73.600000,196.500000,3.823000,19.800000,26.000000,4.331000,0.0
max,540.561000,67.550000,1.000000,82.600000,8.000000,450.000000,138.700000,79.300000,224.500000,5.115000,32.000000,45.000000,6.293000,0.0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   manufact   117 non-null    object
 1   model      117 non-null    object
 2   sales      117 non-null    float64
 3   resale     117 non-null    float64
 4   type       117 non-null    int64
 5   price      117 non-null    float64
 6   engine_s   117 non-null    float64
 7   horsepow   117 non-null    int64
 8   wheelbas   117 non-null    float64
 9   width      117 non-null    float64
 10  length     117 non-null    float64
 11  curb_wgt   117 non-null    float64
 12  fuel_cap   117 non-null    float64
 13  mpg        117 non-null    float64
 14  lnsales    117 non-null    float64
 15  partition  117 non-null    int64
dtypes: float64(11), int64(3), object(2)
memory usage: 14.8+ KB

In [6]:
X=data[['sales','resale','type','engine_s','horsepow','wheelbas','width','length','curb_wgt','fuel_cap','mpg','lnsales','partition']]
y=data['price']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=104)

In [9]:
X_train

,sales,resale,type,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition
111,9.835,34.080,1,4.7,230,112.2,76.4,192.5,5.115,25.4,15.0,2.286,0
42,276.747,16.640,1,4.0,210,111.6,70.2,190.7,3.876,21.0,19.0,5.623,0
39,35.068,8.835,0,2.5,170,106.5,69.1,184.6,2.769,15.0,25.0,3.557,0
5,1.380,39.000,0,4.2,310,113.0,74.0,198.2,3.902,23.7,21.0,0.322,0
18,42.593,11.525,0,3.4,180,110.5,72.7,197.9,3.340,17.0,27.0,3.752,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,113.369,12.760,0,3.8,190,101.3,73.1,183.2,3.203,15.7,24.0,4.731,0
14,11.185,18.225,0,3.0,200,107.4,70.3,194.8,3.770,18.0,22.0,2.415,0
89,24.361,15.240,1,3.4,185,120.0,72.2,201.4,3.948,25.0,22.0,3.193,0
65,42.541,10.395,0,2.4,154,100.8,68.9,175.4,2.910,15.9,24.0,3.750,0
69,11.337,19.125,1,3.5,200,107.3,69.9,186.6,4.520,24.3,18.0,2.428,0

In [10]:
y_train

111    51.728
42     31.930
39     17.035
5      62.000
18     19.390
        ...
38     21.560
14     31.010
89     25.345
65     19.047
69     31.807
Name: price, Length: 70, dtype: float64

In [11]:
X_test

,sales,resale,type,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition
73,67.956,11.030,0,3.0,153,108.5,73.0,199.7,3.379,16.0,24.0,4.219,0
30,71.186,10.185,0,2.5,168,108.0,71.0,186.0,3.058,16.0,24.0,4.265,0
46,540.561,15.075,1,4.6,220,138.5,79.1,224.5,4.241,25.1,18.0,6.293,0
35,111.313,11.260,1,2.5,120,131.0,71.5,215.0,3.557,22.0,19.0,4.712,0
2,8.588,29.725,0,3.5,210,114.6,71.4,196.6,3.850,18.0,22.0,2.150,0
23,7.854,12.360,0,2.5,163,103.7,69.7,190.9,2.967,15.9,24.0,2.061,0
41,63.403,14.210,0,4.6,200,114.7,78.2,212.0,3.908,19.0,21.0,4.150,0
92,24.155,12.025,1,2.4,150,113.3,76.8,186.3,3.528,20.0,24.0,3.184,0
22,21.855,5.160,0,1.0,55,93.1,62.6,149.4,1.895,10.3,45.0,3.084,0
7,17.527,36.125,0,2.8,193,111.4,70.9,188.0,3.472,18.5,24.8,2.864,0
80,3.311,58.600,0,5.0,302,99.0,71.3,177.1,4.125,21.1,20.0,1.197,0
94,131.097,10.290,0,3.4,175,107.0,70.4,186.3,3.091,15.2,25.0,4.876,0
75,27.609,20.430,1,4.0,210,111.6,70.2,190.1,3.876,21.0,18.0,3.318,0
84,27.308,15.380,1,3.3,170,112.2,74.9,194.8,3.991,20.0,21.0,3.307,0
54,29.450,8.910,0,2.4,148,106.3,71.6,185.4,3.072,17.2,25.0,3.383,0
70,39.348,13.880,1,3.0,173,107.3,66.7,178.3,3.510,19.5,20.0,3.672,0
50,12.855,17.525,1,3.2,205,106.4,70.4,178.2,3.857,21.1,19.0,2.554,0
114,51.102,16.725,0,1.8,150,106.4,68.5,184.1,3.043,16.4,27.0,3.934,0
68,0.110,20.940,0,3.0,161,97.2,72.4,180.3,3.131,19.8,21.0,-2.207,0
105,247.994,13.245,0,2.2,133,105.2,70.1,188.5,2.998,18.5,27.0,5.513,0
115,9.569,16.575,0,2.0,115,97.4,66.7,160.4,3.079,13.7,26.0,2.259,0
86,1.112,11.240,0,3.1,150,107.0,69.4,192.0,3.102,15.2,25.0,0.106,0
51,76.029,19.490,1,3.5,210,118.1,75.6,201.2,4.288,20.0,23.0,4.331,0
56,55.557,13.475,1,2.5,120,93.4,66.7,152.0,3.045,19.0,17.0,4.017,0
44,125.338,23.575,1,4.6,240,119.0,78.7,204.6,4.808,26.0,16.0,4.831,0
15,145.519,9.250,0,2.2,115,104.1,67.9,180.9,2.676,14.3,27.0,4.980,0
109,25.106,13.325,1,2.0,127,94.9,66.7,163.8,2.668,15.3,27.0,3.223,0
20,17.947,36.225,0,5.7,345,104.5,73.6,179.7,3.210,19.1,22.0,2.887,0
0,16.919,16.360,0,1.8,140,101.2,67.3,172.4,2.639,13.2,28.0,2.828,0
32,227.061,15.060,1,5.2,230,138.7,79.3,224.2,4.470,26.0,17.0,5.425,0
66,55.616,10.595,0,2.4,145,103.7,68.5,187.8,2.945,16.3,25.0,4.018,0
108,84.087,9.575,1,2.4,142,103.3,66.5,178.7,2.580,15.1,23.0,4.432,0
27,13.462,17.325,0,3.5,253,113.0,74.4,207.7,3.564,17.0,23.0,2.600,0
10,27.851,20.190,0,3.8,205,113.8,74.7,206.8,3.778,18.5,24.0,3.327,0
16,135.126,11.225,0,3.1,170,107.0,69.4,190.4,3.051,15.0,25.0,4.906,0
61,6.375,40.375,0,4.0,290,112.2,72.0,196.7,3.890,22.5,22.0,1.852,0
83,79.853,15.125,0,3.0,222,108.3,70.3,190.5,3.294,18.5,25.0,4.380,0
106,63.849,18.140,0,3.0,210,107.1,71.7,191.9,3.417,18.5,26.0,4.157,0
21,32.299,9.125,0,1.8,120,97.1,66.7,174.3,2.398,13.2,33.0,3.475,0
57,80.556,13.775,1,4.0,190,101.4,69.4,167.5,3.194,20.0,20.0,4.389,0
72,26.529,13.890,0,2.0,125,106.4,69.6,185.0,2.892,16.0,30.0,3.278,0
40,245.815,10.055,0,3.0,155,108.5,73.0,197.6,3.368,16.0,24.0,5.505,0
74,81.174,14.875,0,4.6,200,114.7,78.2,212.0,3.958,19.0,21.0,4.397,0
97,35.945,13.225,0,3.8,205,112.2,72.6,202.5,3.590,17.5,24.0,3.582,0
45,220.650,7.850,1,2.5,119,117.5,69.4,200.7,3.086,20.0,23.0,5.397,0
71,14.351,8.800,0,2.0,125,106.5,69.1,184.8,2.769,15.0,28.0,2.664,0
34,31.038,13.425,1,3.9,175,127.2,78.8,208.5,4.298,32.0,16.0,3.435,0

In [12]:
y_test

73     19.035
30     20.230
46     26.935
35     16.980
2      42.000
23     19.840
41     22.195
92     18.850
22      9.235
7      38.900
80     82.600
94     19.720
75     27.560
84     26.399
54     14.999
70     22.527
50     26.600
114    21.200
68     25.450
105    17.518
115    19.990
86     18.145
51     26.000
56     14.460
44     36.135
15     13.260
109    16.888
20     45.705
0      21.500
32     19.460
66     17.357
108    11.528
27     28.340
10     31.965
16     16.535
61     54.005
83     26.249
106    25.545
21     13.960
57     21.620
72     16.540
40     17.885
74     22.605
97     23.755
45     12.050
71     16.240
34     18.575
Name: price, dtype: float64

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lg=LinearRegression()

In [15]:
lg.fit(X_train,y_train)

LinearRegression()

In [16]:
data.columns

Index(['manufact', 'model', 'sales', 'resale', 'type', 'price', 'engine_s',
       'horsepow', 'wheelbas', 'width', 'length', 'curb_wgt', 'fuel_cap',
       'mpg', 'lnsales', 'partition'],
      dtype='object')

In [17]:
data.head()

,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition
0,Acura,Integra,16.919,16.360,0,21.50,1.8,140,101.2,67.3,172.4,2.639,13.2,28.0,2.828,0
1,Acura,TL,39.384,19.875,0,28.40,3.2,225,108.1,70.3,192.9,3.517,17.2,25.0,3.673,0
2,Acura,RL,8.588,29.725,0,42.00,3.5,210,114.6,71.4,196.6,3.850,18.0,22.0,2.150,0
3,Audi,A4,20.397,22.255,0,23.99,1.8,150,102.6,68.2,178.0,2.998,16.4,27.0,3.015,0
4,Audi,A6,18.780,23.555,0,33.95,2.8,200,108.7,76.1,192.0,3.561,18.5,22.0,2.933,0

In [19]:
a=float(input("Enter the value of sales: "))
b=float(input("Enter the value of resale: "))
c=float(input("Enter the value of type: "))
d=float(input("Enter the value of engine_s: "))
e=float(input("Enter the value of horsepow: "))
f=float(input("Enter the value of wheelbas: "))
g=float(input("Enter the value of width: "))
h=float(input("Enter the value of length: "))
i=float(input("Enter the value of curb_wgt: "))
j=float(input("Enter the value of fuel_cap: "))
k=float(input("Enter the value of mpg: "))
l=float(input("Enter the value of lnsales: "))
m=float(input("Enter the value of partition: "))
d=np.array([[a,b,c,d,e,f,g,h,i,j,k,l,m]])
pred=lg.predict(d)
pred

Enter the value of sales: 16.919
Enter the value of resale: 16.360
Enter the value of type: 0
Enter the value of engine_s: 1.8
Enter the value of horsepow: 140
Enter the value of wheelbas: 101.2
Enter the value of width: 67.3
Enter the value of length: 172.4
Enter the value of curb_wgt: 2.639
Enter the value of fuel_cap: 13.2
Enter the value of mpg: 28.0
Enter the value of lnsales: 2.828
Enter the value of partition: 0

C:\Users\kshyk\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([20.14253107])

In [20]:
a=float(input("Enter the value of sales: "))
b=float(input("Enter the value of resale: "))
c=float(input("Enter the value of type: "))
d=float(input("Enter the value of engine_s: "))
e=float(input("Enter the value of horsepow: "))
f=float(input("Enter the value of wheelbas: "))
g=float(input("Enter the value of width: "))
h=float(input("Enter the value of length: "))
i=float(input("Enter the value of curb_wgt: "))
j=float(input("Enter the value of fuel_cap: "))
k=float(input("Enter the value of mpg: "))
l=float(input("Enter the value of lnsales: "))
m=float(input("Enter the value of partition: "))
d=np.array([[a,b,c,d,e,f,g,h,i,j,k,l,m]])
pred=lg.predict(d)
pred

Enter the value of sales: 16
Enter the value of resale: 16
Enter the value of type: 0
Enter the value of engine_s: 140
Enter the value of horsepow: 101
Enter the value of wheelbas: 67
Enter the value of width: 172
Enter the value of length: 3
Enter the value of curb_wgt: 18
Enter the value of fuel_cap: 27
Enter the value of mpg: 3
Enter the value of lnsales: 0
Enter the value of partition: 0

C:\Users\kshyk\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([163.43822633])